import {
  AppBar,
  Box,
  Button,
  Container,
  Typography,
  Toolbar,
  useTheme,
  useMediaQuery,
  Stack,
  Chip,
  Paper,
} from '@mui/material';
import {
  Groups,
  Edit,
  Share,
  Quiz,
  CheckCircle,
  AutoAwesome,
  TrendingUp,
  School,
  Stars,
  SmartToy,
} from '@mui/icons-material';
import { Link } from 'react-router-dom';
import { ThemeToggle, useTheme as useAppTheme } from '../theme';


const LandingPage = () => {
  const theme = useTheme();
  const { mode } = useAppTheme();
  const isMobile = useMediaQuery(theme.breakpoints.down('md'));

  const features = [
    {
      icon: <Groups />,
      title: 'Workspace Collaboration',
      description: 'Create and join collaborative workspaces with your peers and tutors for seamless group learning.',
      category: 'Collaboration'
    },
    {
      icon: <AutoAwesome />,
      title: 'AI-Powered Study Plans',
      description: 'Get personalized study plans generated by AI, tailored to your learning style and goals.',
      category: 'AI Features'
    },
    {
      icon: <Edit />,
      title: 'Real-Time Document Editing',
      description: 'Collaborate on documents simultaneously with real-time editing and intelligent version control.',
      category: 'Productivity'
    },
    {
      icon: <Share />,
      title: 'Smart Resource Sharing',
      description: 'Share and discover study materials, notes, and resources within your learning community.',
      category: 'Sharing'
    },
    {
      icon: <Quiz />,
      title: 'Interactive Quizzes',
      description: 'Take adaptive quizzes with detailed analytics to track your progress and identify areas for improvement.',
      category: 'Assessment'
    },
    {
      icon: <TrendingUp />,
      title: 'Visual Analytics',
      description: 'Monitor your learning progress with intuitive dashboards and comprehensive performance analytics.',
      category: 'Analytics'
    },
    {
      icon: <Stars />,
      title: 'Gamified Learning',
      description: 'Learn through interactive flashcards and gamification elements that boost engagement and retention.',
      category: 'Engagement'
    },
    {
      icon: <SmartToy />,
      title: '24/7 AI Tutor',
      description: 'Get instant help and personalized explanations from our intelligent AI tutor, available anytime.',
      category: 'Support'
    },
  ];

  const steps = [
    {
      number: '01',
      title: 'Join a Workspace',
      description: 'Create or join collaborative learning spaces with your classmates and instructors.',
    },
    {
      number: '02',
      title: 'Collaborate in Groups',
      description: 'Work together on projects, share resources, and learn from each other.',
    },
    {
      number: '03',
      title: 'Achieve Your Goals',
      description: 'Track progress, get insights, and succeed in your academic journey.',
    },
  ];



  return (
    <Box>
      {/* Navigation */}
      <AppBar 
        position="fixed" 
        elevation={0}
        sx={{ 
          backgroundColor: theme.palette.mode === 'light' 
            ? 'rgba(255, 255, 255, 0.85)' 
            : 'rgba(18, 18, 18, 0.85)', 
          backdropFilter: 'blur(20px)',
          borderBottom: `1px solid ${theme.palette.divider}`,
          transition: 'all 0.3s ease-in-out',
        }}
      >
        <Toolbar sx={{ py: 1.5 }}>
          <Box sx={{ display: 'flex', alignItems: 'center', flexGrow: 1 }}>
            <Box 
              sx={{ 
                backgroundColor: 'primary.main',
                borderRadius: '10px',
                p: 1,
                mr: 2.5,
                display: 'flex',
                alignItems: 'center',
              }}
            >
              <School sx={{ color: 'white', fontSize: '1.4rem' }} />
            </Box>
            <Typography
              variant="h5"
              component="div"
              sx={{ 
                fontWeight: 'bold',
                fontSize: { xs: '1.4rem', sm: '1.7rem' },
                color: 'primary.main'
              }}
            >
              Learni
            </Typography>
          </Box>
          
          {!isMobile && (
            <Box sx={{ display: 'flex', gap: 2, alignItems: 'center' }}>
              <Button 
                variant="text" 
                sx={{ 
                  color: 'text.primary',
                  fontWeight: 500,
                  fontSize: '1rem',
                  textTransform: 'none',
                  px: 2,
                  py: 1,
                }}
              >
                Features
              </Button>
              <Button 
                variant="text" 
                sx={{ 
                  color: 'text.primary',
                  fontWeight: 500,
                  fontSize: '1rem',
                  textTransform: 'none',
                  px: 2,
                  py: 1,
                }}
              >
                Pricing
              </Button>
              <Button 
                component={Link} 
                to="/about"
                variant="text" 
                sx={{ 
                  color: 'text.primary',
                  fontWeight: 500,
                  fontSize: '1rem',
                  textTransform: 'none',
                  px: 2,
                  py: 1,
                }}
              >
                About
              </Button>
              <Button 
                variant="contained" 
                color="primary" 
                component={Link} 
                to="/login"
                sx={{ 
                  ml: 1,
                  px: 3,
                  py: 1,
                  fontWeight: 600,
                  fontSize: '1rem',
                  textTransform: 'none',
                }}
              >
                Login
              </Button>
              <ThemeToggle size="medium" variant='default' />
            </Box>
          )}
          {isMobile && (
            <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
              <Button 
                variant="outlined" 
                color="primary" 
                size="small"
                component={Link} 
                to="/login"
                sx={{ 
                  fontSize: '0.8rem',
                  px: 2,
                  py: 0.7,
                  borderRadius: '20px',
                  fontWeight: 600
                }}
              >
                Login
              </Button>
              <ThemeToggle size="small" />
            </Box>
          )}
        </Toolbar>
      </AppBar>



      {/* Hero Section */}
      <Box
        sx={{
          pt: { xs: 12, sm: 16 },
          pb: { xs: 8, sm: 12 },
          position: 'relative',
          background: mode === 'light' 
            ? 'linear-gradient(180deg, #fafafa 0%, #f5f5f5 100%)'
            : 'linear-gradient(180deg, #121212 0%, #1e1e1e 100%)',
        }}
      >
        <Container maxWidth="lg">
          {/* Main Hero Content */}
          <Box textAlign="left" sx={{ mb: 8 }}>
            <Typography 
              variant="h1" 
              fontWeight="bold" 
              gutterBottom
              sx={{
                fontSize: { xs: '2.5rem', sm: '4rem', md: '5rem' },
                mb: 3,
                color: 'text.primary',
                lineHeight: 1.1,
              }}
            >
              Welcome to{" "} <br/>
              <Box component="span" sx={{ 
                background: 'linear-gradient(135deg, #1976d2 0%, #42a5f5 100%)',
                WebkitBackgroundClip: 'text',
                WebkitTextFillColor: 'transparent',
                backgroundClip: 'text',
              }}>
                Learni
              </Box>
            </Typography>

            <Typography 
              variant="h4" 
              fontWeight="bold" 
              sx={{
                fontSize: { xs: '1.3rem', sm: '1.8rem', md: '2.2rem' },
                mb: 4,
                color: 'text.secondary',
                lineHeight: 1.3,
                
              }}
            >
              Learn Smarter, Together
            </Typography>

            <Typography
              variant="body1"
              color="text.secondary"
              sx={{ 
                mb: 6, 
                lineHeight: 1.8,
                maxWidth: '800px',
                fontSize: { xs: '1.1rem', sm: '1.2rem' }
              }}
            >
              A collaborative learning platform designed to bring{" "}
              <strong>Admins, Tutors, and Students</strong> together in an engaging
              and productive environment. Experience AI-powered study tools, real-time collaboration, 
              and personalized educational experiences — all in one place.
            </Typography>

            <Stack 
              direction={{ xs: 'column', sm: 'row' }} 
              spacing={3} 
              justifyContent="flex-start"
              alignItems={{ xs: 'stretch', sm: 'center' }}
              sx={{ mb: 8 }}
            >
              <Button
                component={Link} 
                to="/login"
                variant="contained"
                size="large"
                sx={{
                  textTransform: 'none',
                  fontSize: '1.1rem',
                  fontWeight: 600,
                  px: 4,
                  py: 1.5,
                  background: 'linear-gradient(135deg, #1976d2 0%, #42a5f5 100%)',
                  boxShadow: '0 4px 12px rgba(25, 118, 210, 0.3)',
                  '&:hover': {
                    background: 'linear-gradient(135deg, #0d47a1 0%, #1976d2 100%)',
                    boxShadow: '0 6px 20px rgba(25, 118, 210, 0.4)',
                    transform: 'translateY(-2px)',
                  },
                  transition: 'all 0.3s ease',
                }}
              >
                Get Started Today
              </Button>
              
              <Button
                component={Link}
                to="/about"
                variant="outlined"
                size="large"
                sx={{
                  textTransform: 'none',
                  fontSize: '1.1rem',
                  fontWeight: 600,
                  px: 4,
                  py: 1.5,
                }}
              >
                Learn More
              </Button>
            </Stack>
          </Box>

          {/* Stats Section */}
          <Box 
            sx={{ 
              display: 'grid',
              gridTemplateColumns: { xs: '1fr', sm: 'repeat(3, 1fr)' },
              gap: 6,
              mb: 8,
              textAlign: 'center'
            }}
          >
            <Box>
              <Typography 
                variant="h2" 
                fontWeight="700" 
                sx={{ 
                  mb: 1,
                  fontSize: { xs: '2.5rem', sm: '3rem' },
                  color: 'primary.main'
                }}
              >
                10K+
              </Typography>
              <Typography 
                variant="body1" 
                color="text.secondary" 
                fontWeight="500"
                sx={{ fontSize: '1.1rem' }}
              >
                Active Students
              </Typography>
            </Box>
            <Box>
              <Typography 
                variant="h2" 
                fontWeight="700" 
                sx={{ 
                  mb: 1,
                  fontSize: { xs: '2.5rem', sm: '3rem' },
                  color: 'primary.dark'
                }}
              >
                500+
              </Typography>
              <Typography 
                variant="body1" 
                color="text.secondary" 
                fontWeight="500"
                sx={{ fontSize: '1.1rem' }}
              >
                Partner Universities
              </Typography>
            </Box>
            <Box>
              <Typography 
                variant="h2" 
                fontWeight="700" 
                sx={{ 
                  mb: 1,
                  fontSize: { xs: '2.5rem', sm: '3rem' },
                  color: 'secondary.main'
                }}
              >
                95%
              </Typography>
              <Typography 
                variant="body1" 
                color="text.secondary" 
                fontWeight="500"
                sx={{ fontSize: '1.1rem' }}
              >
                Success Rate
              </Typography>
            </Box>
          </Box>

          <Box sx={{ mt: 6, pt: 4, borderTop: '1px solid', borderColor: 'divider' }}>
            <Typography variant="caption" color="text.secondary">
              🚀 Built with React, Material-UI, and modern web technologies — empowering collaborative education.
            </Typography>
          </Box>
        </Container>
      </Box>

      {/* Features Section */}
      <Container maxWidth="lg" sx={{ py: { xs: 8, sm: 12 } }}>
        <Box textAlign="center" sx={{ mb: 8 }}>
          <Typography 
            variant="h3" 
            fontWeight="bold" 
            gutterBottom
            sx={{ 
              mb: 3,
              fontSize: { xs: '2rem', sm: '2.5rem', md: '3rem' }
            }}
          >
            Key <Box component="span" sx={{ 
              background: 'linear-gradient(135deg, #1976d2 0%, #42a5f5 100%)',
              WebkitBackgroundClip: 'text',
              WebkitTextFillColor: 'transparent',
              backgroundClip: 'text',
            }}>Features</Box>
          </Typography>
          <Typography
            variant="body1"
            color="text.secondary"
            sx={{ 
              maxWidth: '800px', 
              mx: 'auto',
              lineHeight: 1.8,
              fontSize: { xs: '1.1rem', sm: '1.2rem' }
            }}
          >
            Discover powerful tools designed to enhance your learning experience 
            and boost academic performance through <strong>intelligent collaboration</strong> and AI-powered features.
          </Typography>
        </Box>

        <Box
          sx={{
            display: 'grid',
            gridTemplateColumns: {
              xs: '1fr',
              sm: 'repeat(2, 1fr)',
              lg: 'repeat(4, 1fr)'
            },
            gap: { xs: 3, sm: 4 },
          }}
        >
          {features.map((feature, index) => (
            <Paper
              key={index}
              elevation={0}
              sx={{
                height: '100%',
                p: 3,
                borderRadius: 3,
                background: mode === 'light' 
                  ? 'rgba(255, 255, 255, 0.9)'
                  : 'rgba(255, 255, 255, 0.05)',
                border: `1px solid ${theme.palette.divider}`,
                transition: 'all 0.3s ease',
                '&:hover': {
                  transform: 'translateY(-4px)',
                  boxShadow: '0 8px 25px rgba(0, 0, 0, 0.1)',
                }
              }}
            >
              <Box textAlign="center">
                <Chip
                  label={feature.category}
                  size="small"
                  sx={{
                    mb: 2,
                    fontSize: '0.7rem',
                    fontWeight: 600,
                    color: 'primary.main',
                    backgroundColor: 'rgba(25, 118, 210, 0.08)',
                    border: '1px solid rgba(25, 118, 210, 0.2)',
                  }}
                />
                
                <Box
                  sx={{
                    width: 56,
                    height: 56,
                    borderRadius: '12px',
                    background: 'linear-gradient(135deg, #1976d2 0%, #42a5f5 100%)',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    mx: 'auto',
                    mb: 2,
                    boxShadow: '0 4px 12px rgba(25, 118, 210, 0.25)',
                  }}
                >
                  <Box sx={{ color: 'white', fontSize: '1.5rem' }}>
                    {feature.icon}
                  </Box>
                </Box>
                
                <Typography
                  variant="h6"
                  gutterBottom
                  sx={{ 
                    fontWeight: 600,
                    fontSize: '1.1rem',
                    mb: 1,
                    color: 'text.primary'
                  }}
                >
                  {feature.title}
                </Typography>
                <Typography
                  variant="body2"
                  color="text.secondary"
                  sx={{ 
                    lineHeight: 1.6,
                    fontSize: '0.9rem'
                  }}
                >
                  {feature.description}
                </Typography>
              </Box>
            </Paper>
          ))}
        </Box>
      </Container>

      {/* How It Works Section */}
      <Box sx={{ 
        backgroundColor: mode === 'light' ? 'grey.50' : 'grey.900',
        py: { xs: 8, sm: 12 },
      }}>

        <Container maxWidth="lg">
          <Box textAlign="center" sx={{ mb: 8 }}>
            <Typography 
              variant="h3" 
              fontWeight="bold" 
              gutterBottom
              sx={{ 
                mb: 3,
                fontSize: { xs: '2rem', sm: '2.5rem', md: '3rem' }
              }}
            >
              How <Box component="span" sx={{ 
                background: 'linear-gradient(135deg, #1976d2 0%, #42a5f5 100%)',
                WebkitBackgroundClip: 'text',
                WebkitTextFillColor: 'transparent',
                backgroundClip: 'text',
              }}>Learni</Box> Works
            </Typography>
            <Typography
              variant="body1"
              color="text.secondary"
              sx={{ 
                maxWidth: '800px', 
                mx: 'auto',
                lineHeight: 1.8,
                fontSize: { xs: '1.1rem', sm: '1.2rem' }
              }}
            >
              Get started with Learni in <strong>three simple steps</strong> and transform your learning experience 
              with our intuitive platform designed for modern education.
            </Typography>
          </Box>

          <Box
            sx={{
              display: 'grid',
              gridTemplateColumns: {
                xs: '1fr',
                md: 'repeat(3, 1fr)'
              },
              gap: { xs: 6, md: 4 },
              alignItems: 'stretch',
              position: 'relative',
              '&::before': {
                content: '""',
                position: 'absolute',
                top: '50%',
                left: '16.66%',
                right: '16.66%',
                height: '2px',
                background: `linear-gradient(90deg, transparent 0%, ${theme.palette.primary.main} 20%, ${theme.palette.primary.main} 80%, transparent 100%)`,
                display: { xs: 'none', md: 'block' },
                zIndex: 0,
              }
            }}
          >
            {steps.map((step, index) => (
              <Paper
                key={index}
                elevation={0}
                sx={{
                  textAlign: 'center',
                  p: { xs: 4, sm: 5 },
                  borderRadius: 4,
                  position: 'relative',
                  zIndex: 1,
                  background: mode === 'light' 
                    ? 'rgba(255, 255, 255, 0.9)'
                    : 'rgba(255, 255, 255, 0.02)',
                  backdropFilter: 'blur(10px)',
                  border: `1px solid ${theme.palette.divider}`,
                  transition: 'all 0.4s ease',
                  '&:hover': {
                    transform: 'translateY(-8px)',
                    boxShadow: '0 20px 40px rgba(102, 126, 234, 0.1)',
                    '& .step-number': {
                      transform: 'scale(1.1)',
                      background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
                    }
                  }
                }}
              >
                <Box
                  className="step-number"
                  sx={{
                    width: 80,
                    height: 80,
                    borderRadius: '50%',
                    background: 'linear-gradient(135deg, rgba(102, 126, 234, 0.1) 0%, rgba(118, 75, 162, 0.1) 100%)',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    mx: 'auto',
                    mb: 3,
                    transition: 'all 0.3s ease',
                    border: '2px solid',
                    borderColor: 'primary.main',
                  }}
                >
                  <Typography
                    variant="h4"
                    sx={{
                      fontWeight: 800,
                      color: 'primary.main',
                      fontSize: '1.8rem',
                    }}
                  >
                    {step.number}
                  </Typography>
                </Box>

                <Typography
                  variant="h5"
                  gutterBottom
                  sx={{ 
                    fontWeight: 600,
                    fontSize: { xs: '1.3rem', sm: '1.5rem' },
                    mb: 2
                  }}
                >
                  {step.title}
                </Typography>
                <Typography
                  variant="body1"
                  color="text.secondary"
                  sx={{ 
                    lineHeight: 1.7,
                    fontSize: { xs: '0.95rem', sm: '1rem' }
                  }}
                >
                  {step.description}
                </Typography>
              </Paper>
            ))}
          </Box>
        </Container>
      </Box>

      

      {/* Ready to Get Started Section */}
      <Container maxWidth="lg" sx={{ py: { xs: 8, sm: 12 } }}>
        <Box textAlign="center" sx={{ mb: 8 }}>
          <Typography 
            variant="h3" 
            fontWeight="bold" 
            gutterBottom
            sx={{ 
              mb: 3,
              fontSize: { xs: '2rem', sm: '2.5rem', md: '3rem' }
            }}
          >
            Ready to Get <Box component="span" sx={{ 
              background: 'linear-gradient(135deg, #1976d2 0%, #42a5f5 100%)',
              WebkitBackgroundClip: 'text',
              WebkitTextFillColor: 'transparent',
              backgroundClip: 'text',
            }}>Started</Box>?
          </Typography>
          <Typography
            variant="body1"
            color="text.secondary"
            sx={{ 
              maxWidth: '800px', 
              mx: 'auto',
              lineHeight: 1.8,
              fontSize: { xs: '1.1rem', sm: '1.2rem' },
              mb: 6
            }}
          >
            Join over <strong>10,000 students and tutors</strong> who are already using Learni 
            to achieve their academic goals. Start your educational journey today!
          </Typography>

          <Stack 
            direction={{ xs: 'column', sm: 'row' }} 
            spacing={3} 
            justifyContent="center"
            alignItems="center"
            sx={{ mb: 6 }}
          >
            <Button
              component={Link}
              to="/login"
              variant="contained"
              size="large"
              endIcon={<CheckCircle />}
              sx={{
                textTransform: 'none',
                fontSize: '1.1rem',
                fontWeight: 600,
                px: 4,
                py: 1.5,
                background: 'linear-gradient(135deg, #1976d2 0%, #42a5f5 100%)',
                boxShadow: '0 4px 12px rgba(25, 118, 210, 0.3)',
                '&:hover': {
                  background: 'linear-gradient(135deg, #0d47a1 0%, #1976d2 100%)',
                  boxShadow: '0 6px 20px rgba(25, 118, 210, 0.4)',
                  transform: 'translateY(-2px)',
                },
                transition: 'all 0.3s ease',
              }}
            >
              Start Learning Free
            </Button>
            <Button
              component={Link}
              to="/about"
              variant="outlined"
              size="large"
              sx={{
                textTransform: 'none',
                fontSize: '1.1rem',
                fontWeight: 600,
                px: 4,
                py: 1.5,
                borderColor: 'primary.main',
                color: 'primary.main',
                borderWidth: 2,
                '&:hover': {
                  borderColor: 'primary.dark',
                  color: 'primary.dark',
                  backgroundColor: 'rgba(25, 118, 210, 0.04)',
                  borderWidth: 2,
                  transform: 'translateY(-1px)',
                },
                transition: 'all 0.3s ease',
              }}
            >
              Schedule Demo
            </Button>
          </Stack>

          {/* Trust indicators */}
          <Stack 
            direction={{ xs: 'column', sm: 'row' }} 
            spacing={4} 
            justifyContent="center"
            alignItems="center"
            sx={{ opacity: 0.7 }}
          >
            <Typography variant="body2" sx={{ display: 'flex', alignItems: 'center', gap: 1, color: 'text.secondary' }}>
              <CheckCircle sx={{ fontSize: '1rem', color: 'primary.main' }} /> Free 30-day trial
            </Typography>
            <Typography variant="body2" sx={{ display: 'flex', alignItems: 'center', gap: 1, color: 'text.secondary' }}>
              <CheckCircle sx={{ fontSize: '1rem', color: 'primary.main' }} /> No credit card required
            </Typography>
            <Typography variant="body2" sx={{ display: 'flex', alignItems: 'center', gap: 1, color: 'text.secondary' }}>
              <CheckCircle sx={{ fontSize: '1rem', color: 'primary.main' }} /> Cancel anytime
            </Typography>
          </Stack>
        </Box>
      </Container>

      {/* Footer */}
      <Box
        sx={{
          backgroundColor: 'grey.900',
          color: 'white',
          py: { xs: 4, sm: 6 },
          textAlign: 'center',
        }}
      >
        <Container maxWidth="lg">
          <Typography 
            variant="body2" 
            sx={{ 
              opacity: 0.8,
              fontSize: '0.9rem'
            }}
          >
            © {new Date().getFullYear()} <strong>Learni</strong>. All rights reserved. 
            <br />
            🚀 Built with React, Material-UI, and modern web technologies — empowering collaborative education.
          </Typography>
        </Container>
      </Box>
    </Box>
  );
};

export default LandingPage;
